### ISSUE TITLE
result's not correct

### ISSUE THREAD

**Issue by LeeKuo1990** [Mostro-Complexity/depth-pose-estimation#2]
i used your code, not changed anywhere, and used CAD-60 dataset for test, but i can't get the right result as you shown, something wrong with your code or models?

**Comment by Mostro-Complexity** [comment]
This code is not implemented by me actually. I only made some changes to the original code.The experimental results may not ideal.
I prefor you to refer the original repo: https://github.com/ddxue/depth-pose-estimation project.
