### ISSUE TITLE
Seeking cad-60 database

### ISSUE THREAD

**Issue by hailiwang123** [Mostro-Complexity/depth-pose-estimation#3]
Hello, I found out http://pr.cs.cornell.edu/humanactivities/data.php The website cannot be accessed, so the cad-60 database cannot be downloaded. I would like to know if you have the database available to me? Thank you very much.

**Comment by Mostro-Complexity** [comment]
链接：https://pan.baidu.com/s/1JHDee_7OBF5jgL68j0Idnw 
提取码：ludz 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by hailiwang123** [comment]
Thank you very much for your letter.

**Comment by zay95** [comment]
> 链接：https://pan.baidu.com/s/1JHDee_7OBF5jgL68j0Idnw 提取码：ludz 复制这段内容后打开百度网盘手机App，操作更方便哦
Hello， the baiduyun link here  just has  the  file--data2,  could you please offer the data1--data4? Thank you!
